varsion: 2.1
jobs:
    build-modules:
        docker: 
            - image: circleci/node:10.16.3  
        steps:
            - checkout
            - run: npm install
            - persist_to_workspace:
                root: .
                paths:
                    - node_modules

    
orbs:
    docker: circleci/docker@1.4.0

workflows:
    version: 2
    test:
        jobs:
            - build-modules
        
