varsion: 2.1
jobs:
    build-modules:
        docker: 
            - image: circleci/node:10.16.3  
        steps:
            - checkout
            - run: npm install
            - persist_to_workspace:
                root: .
                paths:
                    - node_modules

    unit-test:
        docker: 
            - image: circleci/node:10.16.3    
        working_directory: ~/files
        steps:
            - checkout
            - attach_workspace:
                at: files
            - run: npm test

    
orbs:
    docker: circleci/docker@1.4.0

workflows:
    version: 2
    test:
        jobs:
            - build-modules
            - unit-test:
                requires:
                    - build-modules

